version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Passw0rd!" # Güvenli bir şifre kullanmayı unutmayın
      POSTGRES_DB: "gelirgiderbot"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
